name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8 # adjust if project uses different pnpm version

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run Lint (if script exists)
        run: pnpm run lint --if-present

      - name: Run Tests (if script exists)
        run: pnpm test --if-present
