name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Enable Corepack and prepare pnpm
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate
          pnpm --version

      - name: Install dependencies
        run: |
          if [ -f pnpm-lock.yaml ]; then
            pnpm install --frozen-lockfile
          else
            npm ci
          fi

      - name: Run Lint (if present)
        run: |
          if [ -f pnpm-lock.yaml ]; then
            pnpm run lint --if-present
          else
            npm run lint --if-present
          fi

      - name: Run Tests (if present)
        run: |
          if [ -f pnpm-lock.yaml ]; then
            pnpm test --if-present
          else
            npm test --if-present
          fi
